server:
  port: 8110 # 服务端口

spring:
  profiles:
    active: dev # 环境设置
  application:
    name: service-core # 服务名
  datasource: # mysql数据库连接
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_srb_core?serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password: 123456
  redis:
    host: 192.168.2.130
    port: 6379
    database: 0
    timeout: 3000ms
    lettuce:
      pool:
        max-active: 20 #连接池中最大连接数
        max-wait: -1 #连接池最大阻塞等待时间
        max-idle: 10 #连接池中的最大空闲连接
        min-idle: 0 #连接池中最小空闲连接数
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

mybatis-plus: #mybatis
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml

# 设置日志级别
#logging:
#  level:
#    root: ERROR